### PR TITLE
Keyword Filter

### PR DESCRIPTION
**Pull request by Kamiikaze**
This Feature allows the user to add keywords on the option-panel. Links containing one of those keywords are getting filtered out.

### Example:
**Filter URLs or Media Types (seperated by comma)**
".ts,w3schools,"

Will filter out all links containing "w3schools" or ending with ".ts".

### CODE REVIEW

**Review by SidBlack — APPROVED** [review]

**Comment by Kamiikaze** [comment]
Will this be a feature anytime?

**Comment by andy-portmen** [comment]
@Kamiikaze Some part of this PR is restyling. Please follow the original code styling and resubmit.

**Comment by Kamiikaze** [comment]
Since there is a lot of time passed and you moved to v3 it would be better closing this PR and creating a new one.
Do you have a style guide or eslint config? Cuz' the formattings are default from my IDEA

**Comment by andy-portmen** [comment]
I am using

```js
module.exports = {
  'extends': [
    'eslint:recommended',
    'eslint-config-google'
  ]
};
```

**Pull request closed without merging**
